version: 2

sources:
  - name: jaffle_shop
    description: Raw data from Jaffle Shop (simulating your channel data sources)
    # In production, this would be your actual source tables:
    # - Google Hotel Ads tables
    # - Kayak tables  
    # - Trivago tables
    schema: dev
    tables:
      - name: jaffle_shop_customers
        identifier: jaffle_shop_customers
        description: Raw customer data
      - name: jaffle_shop_orders
        identifier: jaffle_shop_orders
        description: Raw order data
        # PR #3 will convert order_date from JST (Japan Standard Time, UTC+9) to UTC date
      - name: jaffle_shop_payments
        identifier: jaffle_shop_payments
        description: Raw payment data

